Repository siderolabs/sidero, pull requests merged in 2021-12, with the labels that each got.

#650 feat: implement Talos kernel log receiver
  Dockerfile
  Makefile
  app/sidero-controller-manager/cmd/log-receiver/handler.go
  app/sidero-controller-manager/cmd/log-receiver/kubernetes.go
  app/sidero-controller-manager/cmd/log-receiver/main.go
  app/sidero-controller-manager/cmd/siderolink-manager/main.go
  app/sidero-controller-manager/config/manager/manager.yaml
  app/sidero-controller-manager/internal/ipxe/ipxe_server.go
  app/sidero-controller-manager/internal/siderolink/siderolink.go
  app/sidero-controller-manager/main.go
  go.mod
  go.sum
  sfyra/go.mod
  sfyra/go.sum
  website/content/docs/v0.5/Getting Started/create-workload.md
  website/content/docs/v0.5/Resource Configuration/environments.md
Labels: status/approved

#656 feat: implement events manager container
  Dockerfile
  app/sidero-controller-manager/cmd/events-manager/adapter.go
  app/sidero-controller-manager/cmd/events-manager/kubernetes.go
  app/sidero-controller-manager/cmd/events-manager/main.go
  app/sidero-controller-manager/config/manager/manager.yaml
  app/sidero-controller-manager/internal/ipxe/ipxe_server.go
  app/sidero-controller-manager/internal/siderolink/siderolink.go
Labels: status/approved

#657 fix: check for server power state when in use
  app/sidero-controller-manager/controllers/server_controller.go
  app/sidero-controller-manager/pkg/constants/constants.go
Labels: status/ok-to-test

#660 test: fix compatibility by locking down v1alpha3 provider versions
  sfyra/cmd/sfyra/cmd/options.go
Labels: status/ok-to-test

#659 fix: check for server power state when in use
  app/sidero-controller-manager/controllers/server_controller.go
  app/sidero-controller-manager/pkg/constants/constants.go
Labels: status/ok-to-test

#664 release(v0.3.3): prepare release
  CHANGELOG.md
  hack/release.toml
Labels: status/ok-to-test

#666 docs: reflect sidero runs on ARM
  website/content/docs/v0.3/Getting Started/index.md
  website/content/docs/v0.4/Getting Started/index.md
  website/content/docs/v0.5/Getting Started/index.md
Labels: status/ok-to-test

#668 feat: provide a way to configure IPMI PXE method
  app/sidero-controller-manager/config/manager/manager.yaml
  app/sidero-controller-manager/controllers/server_controller.go
  app/sidero-controller-manager/internal/power/api/api.go
  app/sidero-controller-manager/internal/power/factory.go
  app/sidero-controller-manager/internal/power/fake.go
  app/sidero-controller-manager/internal/power/ipmi/ipmi.go
  app/sidero-controller-manager/internal/power/metal/metal.go
  app/sidero-controller-manager/main.go
  hack/release.toml
  website/content/docs/v0.5/Overview/installation.md
Labels: status/ok-to-test

#667 feat: extend information printed in the iPXE script, add retries
  app/sidero-controller-manager/internal/ipxe/ipxe_server.go
  app/sidero-controller-manager/internal/ipxe/ipxe_test.go
Labels: status/ok-to-test

#671 release(v0.4.1-beta.0): prepare release
  CHANGELOG.md
  hack/release.toml
Labels: status/ok-to-test

#676 fix: wait for link up in iPXE script
  Makefile
  app/sidero-controller-manager/internal/api/api.pb.go
  app/sidero-controller-manager/internal/api/api_grpc.pb.go
  app/sidero-controller-manager/internal/ipxe/ipxe_server.go
Labels: status/ok-to-test

#678 feat: additional printer colums
  app/caps-controller-manager/api/v1alpha3/metalcluster_types.go
  app/caps-controller-manager/api/v1alpha3/metalmachine_types.go
  app/caps-controller-manager/api/v1alpha3/serverbinding_types.go
  app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_metalclusters.yaml
  app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_metalmachines.yaml
  app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_serverbindings.yaml
  app/sidero-controller-manager/api/v1alpha1/environment_types.go
  app/sidero-controller-manager/api/v1alpha1/server_types.go
  app/sidero-controller-manager/api/v1alpha1/serverclass_types.go
  app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_environments.yaml
  app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_serverclasses.yaml
  app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
Labels: status/ok-to-test

#679 fix: ensure we setup BMC info *after* disk wiping
  app/sidero-controller-manager/cmd/agent/main.go
Labels: status/ok-to-test

#677 fix: use environment variables in the ipmitool
  go.mod
  go.sum
  sfyra/go.mod
  sfyra/go.sum
Labels: status/ok-to-test

#681 release(v0.5.0-alpha.0): prepare release
  .conform.yaml
  CHANGELOG.md
  config/metadata/metadata.yaml
  hack/release.toml
Labels: status/ok-to-test

#683 release(v0.4.1): prepare release
  CHANGELOG.md
Labels: status/ok-to-test

#670 docs: update docs for upcoming Sidero 0.4.1 release
  website/content/docs/v0.4/Guides/first-cluster.md
  website/content/docs/v0.4/Overview/installation.md
  website/content/docs/v0.4/Resource Configuration/environments.md
  website/content/docs/v0.5/Guides/first-cluster.md
Labels: status/ok-to-test

#690 docs: add patching examples
  website/content/docs/v0.4/Guides/patching.md
  website/content/docs/v0.4/Resource Configuration/metadata.md
  website/content/docs/v0.5/Guides/patching.md
  website/content/docs/v0.5/Resource Configuration/metadata.md
Labels: status/ok-to-test

#691 docs: fix patching examples
  website/content/docs/v0.4/Resource Configuration/metadata.md
  website/content/docs/v0.5/Resource Configuration/metadata.md
Labels: status/ok-to-test, status/ok-to-merge

#662 feat: populate addresses and hostname in ServerBindings
  app/caps-controller-manager/api/v1alpha2/zz_generated.conversion.go
  app/caps-controller-manager/api/v1alpha3/metalcluster_types.go
  app/caps-controller-manager/api/v1alpha3/metalmachine_conditions.go
  app/caps-controller-manager/api/v1alpha3/metalmachine_types.go
  app/caps-controller-manager/api/v1alpha3/serverbinding_types.go
  app/caps-controller-manager/api/v1alpha3/zz_generated.deepcopy.go
  app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_metalmachines.yaml
  app/caps-controller-manager/config/crd/bases/infrastructure.cluster.x-k8s.io_serverbindings.yaml
  app/caps-controller-manager/controllers/metalmachine_controller.go
  app/caps-controller-manager/main.go
  app/sidero-controller-manager/api/v1alpha1/server_types.go
  app/sidero-controller-manager/api/v1alpha1/zz_generated.deepcopy.go
  app/sidero-controller-manager/cmd/events-manager/adapter.go
  app/sidero-controller-manager/cmd/events-manager/kubernetes.go
  app/sidero-controller-manager/cmd/events-manager/main.go
  app/sidero-controller-manager/cmd/log-receiver/handler.go
  app/sidero-controller-manager/config/crd/bases/metal.sidero.dev_servers.yaml
  app/sidero-controller-manager/controllers/server_controller.go
  app/sidero-controller-manager/internal/ipxe/ipxe_server.go
  app/sidero-controller-manager/internal/server/server.go
  app/sidero-controller-manager/main.go
  config/kustomization.yaml
  config/metadata/metadata.yaml
  go.mod
  go.sum
  hack/release.toml
  internal/client/client.go
  sfyra/cmd/sfyra/cmd/options.go
  sfyra/go.mod
  sfyra/go.sum
  sfyra/pkg/capi/check.go
  sfyra/pkg/capi/cluster.go
  sfyra/pkg/capi/metalclient.go
  sfyra/pkg/loadbalancer/loadbalancer.go
  sfyra/pkg/tests/cluster_utils.go
  sfyra/pkg/tests/match.go
  sfyra/pkg/tests/reconcile.go
  sfyra/pkg/tests/scale.go
  templates/cluster-template.yaml
Labels: status/ok-to-test, status/ok-to-merge
